CREATE TABLE IF NOT EXISTS up_calendar_team
(
    ID INT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255),
    ID_ADMIN INT NOT NULL,
	PERSONAL_PHOTO INT,
    IS_PRIVATE BIT,
	PRIMARY KEY (ID),
 	FOREIGN KEY (ID_ADMIN) REFERENCES b_user (ID),
	FOREIGN KEY (PERSONAL_PHOTO) REFERENCES b_file (ID)
);

CREATE TABLE IF NOT EXISTS up_calendar_event
(
    ID INT NOT NULL AUTO_INCREMENT,
    ID_TEAM INT NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    DATE_TIME DATETIME NOT NULL,
 	PRIMARY KEY (ID),
	FOREIGN KEY (ID_TEAM) REFERENCES up_calendar_team (ID)
);

CREATE TABLE IF NOT EXISTS up_calendar_regular_event
(
	ID INT NOT NULL AUTO_INCREMENT,
	ID_TEAM INT NOT NULL,
	TITLE VARCHAR(255) NOT NULL,
	DATE_TIME DATETIME NOT NULL,
	DAY_STEP INT NOT NULL,
	DATE_END DATE,
	PRIMARY KEY (ID),
	FOREIGN KEY (ID_TEAM) REFERENCES up_calendar_team (ID)
);

CREATE TABLE IF NOT EXISTS up_calendar_changed_event
(
	ID INT NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(255) NOT NULL,
	ID_TEAM INT NOT NULL,
	DATE_TIME DATETIME NOT NULL,
 	PRIMARY KEY (ID),
	FOREIGN KEY (ID_TEAM) REFERENCES up_calendar_team (ID)
);

CREATE TABLE IF NOT EXISTS up_calendar_user_story
(
	ID INT NOT NULL AUTO_INCREMENT,
	ID_USER INT NOT NULL,
	DATE_TIME DATETIME NOT NULL,
	ID_TEAM INT NOT NULL,
	TITLE_TEAM VARCHAR(255) NOT NULL,
	TITLE_EVENT VARCHAR(255) NOT NULL,
 	PRIMARY KEY (ID),
 	FOREIGN KEY (ID) REFERENCES b_user (ID),
 	FOREIGN KEY (ID_TEAM) REFERENCES up_calendar_team (ID)
);

CREATE TABLE IF NOT EXISTS up_calendar_user_team
(
  ID_USER INT,
  ID_TEAM INT,
  PRIMARY KEY (ID_USER,ID_TEAM),
  FOREIGN KEY (ID_USER) REFERENCES b_user (ID),
  FOREIGN KEY (ID_TEAM) REFERENCES up_calendar_team (ID)
);

